### ISSUE TITLE
Make price-oracle collectors config more flexible (for add native currency)

### ISSUE THREAD

**Issue by stupid-boar** [crypto-pepe/price-oracle#7]
```yaml
- ...
   tickers:
     - ticker: "BTCUSDT"
       alias: "BTC"
       inverted: false
```

`inverted` = 1/price (optional)
`alias` = rename ticker on collect (optional)
